package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/bfrancisco/quotes-api-app/internal/quotes/model"
	"github.com/bfrancisco/quotes-api-app/internal/service"
	"github.com/bfrancisco/quotes-api-app/internal/transport/graphql/generated"
)

// CreateQuote is the resolver for the createQuote field.
func (r *mutationResolver) CreateQuote(ctx context.Context, input generated.CreateQuoteInput) (*model.Quote, error) {
	quote, err := r.quoteService.CreateQuote(ctx, model.QuoteCreateInput{
		Text:   input.Text,
		Author: input.Author,
	})
	if err != nil {
		return nil, err
	}

	return &quote, nil
}

// UpdateQuote is the resolver for the updateQuote field.
func (r *mutationResolver) UpdateQuote(ctx context.Context, id string, input generated.UpdateQuoteInput) (*model.Quote, error) {
	quote, err := r.quoteService.UpdateQuote(ctx, model.QuoteUpdateInput{
		ID:     id,
		Text:   input.Text,
		Author: input.Author,
	})
	if err != nil {
		return nil, err
	}

	return &quote, nil
}

// DeleteQuote is the resolver for the deleteQuote field.
func (r *mutationResolver) DeleteQuote(ctx context.Context, id string) (bool, error) {
	if err := r.quoteService.DeleteQuote(ctx, id); err != nil {
		return false, err
	}

	return true, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*generated.HealthStatus, error) {
	return &generated.HealthStatus{Status: "ok"}, nil
}

// Quote is the resolver for the quote field.
func (r *queryResolver) Quote(ctx context.Context, id string) (*model.Quote, error) {
	quote, err := r.quoteService.GetQuoteByID(ctx, id)
	if err != nil {
		return nil, err
	}

	return &quote, nil
}

// Quotes is the resolver for the quotes field.
func (r *queryResolver) Quotes(ctx context.Context, author *string, limit *int, offset *int) (*generated.QuotePage, error) {
	input := service.QuoteListInput{}
	if author != nil {
		input.Author = *author
	}
	if limit != nil {
		input.Limit = *limit
	}
	if offset != nil {
		input.Offset = *offset
	}

	result, err := r.quoteService.ListQuotes(ctx, input)
	if err != nil {
		return nil, err
	}

	quotes := make([]*model.Quote, len(result.Quotes))
	for index := range result.Quotes {
		quotes[index] = &result.Quotes[index]
	}

	return &generated.QuotePage{
		Quotes: quotes,
		Count:  result.Count,
		Limit:  result.Limit,
		Offset: result.Offset,
	}, nil
}

// RandomQuote is the resolver for the randomQuote field.
func (r *queryResolver) RandomQuote(ctx context.Context) (*model.Quote, error) {
	quote, err := r.quoteService.GetRandomQuote(ctx)
	if err != nil {
		return nil, err
	}

	return &quote, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
